version: '3.8'

volumes:
  data:

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "171819"
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data